### PR TITLE
initialized summer2024 bootcamp material for week1

### PR DESCRIPTION
**Pull request by juannat7**
1. I initialized `Lectures/Summer2024_Bootcamp/Week_1` and `Codes/Summer2024_Bootcamp/Week_1`, and prepoulating them with adapted notebooks from (https://earth-env-data-science.github.io) -- How do I properly cite their work in my notebooks?

2. Updated README by moving previous bootcamp under the `Past Events` section, and putting a placeholder for the Summer 2024 Bootcamp

TODO: add the `ngbitpuller` once I have access to the folder link (i.e., once its merged)

### CODE REVIEW

**Comment by jbusecke** [comment]
Can you resolve the conflicts in the README?

**Comment by jbusecke** [comment]
> How do I properly cite their work in my notebooks?

Seems to be an open issue: https://github.com/earth-env-data-science/earth-env-data-science-book/issues/46 . Not sure what to recommend here other than for now citing the website of the book.

**Comment by jbusecke** [comment]
These notebooks look amazing @juannat7! Great work. Ill merge this once the conflict is resolved.

**Comment by juannat7** [comment]
Thanks @jbusecke I have resolved the conflict... I will make further updates to the material this coming week

**Comment by jbusecke** [comment]
Amazing. Ill merge and make you a maintainer here, so you are not blocked by me.

**Pull request merged**
